# Reddit eWOM — r/gaming Hype Scraper

For each unique game in `../games_master_player_counts.csv`, search r/gaming top posts (all time) where the game's name appears in the title. Keeping only posts created between **2021-01-01 and 2025-12-31**. 

Results:
- `games_reddit.csv` — one row per game (engagement, valence, n_posts)
- `reddit_posts.csv` — one row per matching post (title, score, upvote_ratio, num_comments, created_utc, permalink)

Using Reddit's public JSON endpoints, with a 1.1s delay between requests to stay under 60/min.

## 1. Setup

In [ ]:
import re
import time
import requests
import pandas as pd
from pathlib import Path

USER_AGENT = "SoCoFinalProject/0.1 by /u/CalendarExotic9775"
GAMES_CSV = Path("../games_with_aliases.csv")
OUTPUT_CSV = Path("games_reddit.csv")
POSTS_CSV = Path("reddit_posts.csv")
SEARCH_URL = "https://www.reddit.com/r/gaming/search.json"

REQUEST_DELAY = 1.1
TOP_N_FOR_VALENCE = 50
MAX_GAMES = 1923      

DATE_MIN_UTC = pd.Timestamp("2021-01-01").timestamp()
DATE_MAX_UTC = pd.Timestamp("2026-01-01").timestamp()

ALIASES = {}

## 2. Load Games + Aliases

In [ ]:
games_list = pd.read_csv(GAMES_CSV)
games_list = games_list.sort_values("peak_players", ascending=False).reset_index(drop=True)

ALIASES = {}
for _, row in games_list.iterrows():
    raw = row.get("aliases")
    if isinstance(raw, str) and raw.strip():
        ALIASES[row["game_name"]] = [a.strip() for a in raw.split("|") if a.strip()]

print(f"Unique games loaded:        {len(games_list):,}")
print(f"Games with ≥1 alias:        {sum(1 for v in ALIASES.values() if v):,}")
print(f"Total alias entries:        {sum(len(v) for v in ALIASES.values()):,}")
print(f"Will process top {MAX_GAMES} by peak_players")

games_list = games_list.head(MAX_GAMES)
games_list[["app_id", "game_name", "peak_players", "num_aliases", "aliases"]].head(10)

Unique games loaded:        1,923
Games with ≥1 alias:        150
Total alias entries:        201
Will process top 1923 by peak_players

,app_id,game_name,peak_players,num_aliases,aliases
0,751780,Forager,999,0,NaN
1,8500,EVE Online,999,0,NaN
2,628070,Romance of the Three Kingdoms XI with Power Up...,999,0,NaN
3,368500,Assassin's Creed Syndicate,999,0,NaN
4,366220,Wurm Unlimited,999,0,NaN
5,500,Left 4 Dead,999,0,NaN
6,1672740,崩壊3rd,999,0,NaN
7,1118200,People Playground,999,0,NaN
8,838350,太吾绘卷 The Scroll Of Taiwu,999,0,NaN
9,1313860,EA SPORTS™ FIFA 21,999,1,FIFA 21

## 3. Reddit Search Helper

Hits r/gaming's search endpoint with the game name as an exact-phrase query, sorted by top of all time. Returns the raw post records from the JSON response.

In [3]:
def _strip_symbols_and_quotes(s: str) -> str:
    s = re.sub(r"[™®©℠]", "", s)
    s = s.replace("‘", "'").replace("’", "'")
    s = s.replace("“", '"').replace("”", '"')
    return s

def normalize_name(s: str) -> str:
    """Normalize a game name (used for search query and regex pattern). Strips parentheticals like '(2007)'."""
    if not s:
        return ""
    s = _strip_symbols_and_quotes(s)
    s = re.sub(r"\s*\([^)]*\)", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

def normalize_title(s: str) -> str:
    """Normalize a Reddit post title. Keeps parentheticals because the game name may be inside them."""
    if not s:
        return ""
    s = _strip_symbols_and_quotes(s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

def search_reddit(name: str, limit: int = 100) -> list[dict]:
    params = {
        "q": f'"{normalize_name(name)}"',
        "restrict_sr": "1",
        "sort": "top",
        "t": "all",
        "limit": str(limit),
    }
    headers = {"User-Agent": USER_AGENT}

    for attempt in range(3):
        r = requests.get(SEARCH_URL, params=params, headers=headers, timeout=20)
        if r.status_code == 200:
            data = r.json()
            return [child["data"] for child in data.get("data", {}).get("children", [])]
        if r.status_code == 429:
            time.sleep(5 * (attempt + 1))
            continue
        r.raise_for_status()
    return []

## 4. Title Matching

A post counts as a match only if the game's name appears as a whole word in the title.

In [ ]:
def title_matches(title: str, name: str) -> bool:
    pattern = re.escape(normalize_name(name))
    return re.search(pattern, normalize_title(title), flags=re.IGNORECASE) is not None

## 5. Per-game Metrics

For one game: build a list of search terms (the dataset name + any aliases from the `ALIASES` dict), hit Reddit's search for each, deduplicate posts by id, keep only those whose title matches one of the variants (word-boundary, normalized), and only those created within the 2021–2025 window. Then compute engagement (sum of upvotes) and valence (mean upvote_ratio of the top 50 by upvotes).

Normalization strips `™ ® © ℠`, unifies curly quotes, drops parentheticals like `(2007)`, and collapses whitespace, so e.g. `Age of Empires III (2007)` will match a Reddit title like `Just played Age of Empires III last night`.

Also returns the raw matched posts so the main loop can save per-post records (title, score, upvote ratio, comment count, post date, permalink) to a separate CSV.

In [5]:
def in_window(post: dict) -> bool:
    ts = post.get("created_utc")
    return ts is not None and DATE_MIN_UTC <= ts < DATE_MAX_UTC

def compute_metrics(name: str) -> dict:
    search_terms = [name] + ALIASES.get(name, [])

    seen_ids = set()
    all_posts = []
    for j, term in enumerate(search_terms):
        if j > 0:
            time.sleep(REQUEST_DELAY)
        for p in search_reddit(term):
            pid = p.get("id")
            if pid and pid not in seen_ids:
                seen_ids.add(pid)
                all_posts.append(p)

    matched = [
        p for p in all_posts
        if any(title_matches(p.get("title", ""), t) for t in search_terms)
        and in_window(p)
    ]

    if not matched:
        return {"engagement": 0, "valence": float("nan"), "n_posts": 0, "posts": []}

    engagement = sum(p.get("score", 0) for p in matched)
    top = sorted(matched, key=lambda p: p.get("score", 0), reverse=True)[:TOP_N_FOR_VALENCE]
    ratios = [p.get("upvote_ratio", 0.0) for p in top if p.get("upvote_ratio") is not None]
    valence = sum(ratios) / len(ratios) if ratios else float("nan")

    return {
        "engagement": engagement,
        "valence": valence,
        "n_posts": len(matched),
        "posts": matched,
    }

## 6. Testrun

In [6]:
for name in games_list["game_name"].head(20):
    m = compute_metrics(name)
    print(f"{name:<40}  engagement={m['engagement']:>7}  valence={m['valence']:.3f}  n={m['n_posts']}")
    time.sleep(REQUEST_DELAY)

Forager                                   engagement=      3  valence=0.545  n=2
EVE Online                                engagement=  18130  valence=0.915  n=4
Romance of the Three Kingdoms XI with Power Up Kit  engagement=      0  valence=nan  n=0
Assassin's Creed Syndicate                engagement=   1537  valence=0.810  n=5
Wurm Unlimited                            engagement=      0  valence=nan  n=0
Left 4 Dead                               engagement= 162238  valence=0.905  n=13
崩壊3rd                                     engagement=      0  valence=nan  n=0
People Playground                         engagement=     50  valence=0.686  n=9
太吾绘卷 The Scroll Of Taiwu                  engagement=      0  valence=nan  n=0
EA SPORTS™ FIFA 21                        engagement=    508  valence=0.599  n=22
The Elder Scrolls IV: Oblivion Game of the Year Edition (2009)  engagement= 581311  valence=0.917  n=54
Plants vs. Zombies: Battle for Neighborville™  engagement=      7  valence=0.597  n=3
Monopoly Plus                             engagement=      2  valence=0.590  n=2
Sid Meier's Civilization IV               engagement=      0  valence=nan  n=0
Warface: Clutch                           engagement=      0  valence=nan  n=0
Worms W.M.D                               engagement=      0  valence=nan  n=0
Pacify                                    engagement=      5  valence=0.710  n=2
Black Mesa                                engagement=   3320  valence=0.938  n=6
rFactor 2                                 engagement=      0  valence=nan  n=0
MapleStory                                engagement=     90  valence=0.818  n=6

## 7. Full Run

Loop over all selected games. Sleeps `REQUEST_DELAY` seconds between requests.

Results:
- `games_2023_reddit.csv` — one row per game with `engagement`, `valence`, `n_posts`.
- `reddit_posts.csv` — one row per matching post with `app_id`, `game_name`, `title`, `score`, `upvote_ratio`, `num_comments`, `created_utc`, `permalink`.

In [7]:
def safe_read_csv(path):
    """Read CSV, return empty DataFrame if file is missing or empty."""
    if not path.exists() or path.stat().st_size == 0:
        return pd.DataFrame()
    try:
        return pd.read_csv(path)
    except pd.errors.EmptyDataError:
        return pd.DataFrame()

done = safe_read_csv(OUTPUT_CSV)
if not done.empty:
    done_names = set(done["game_name"])
    results = done.to_dict(orient="records")
    print(f"Resuming — {len(done)} games already done.")
else:
    done_names = set()
    results = []

posts_existing = safe_read_csv(POSTS_CSV)
posts_records = posts_existing.to_dict(orient="records") if not posts_existing.empty else []
if posts_records:
    print(f"Loaded {len(posts_records)} existing post records.")

for i, row in games_list.iterrows():
    name = row["game_name"]
    if name in done_names:
        continue

    try:
        m = compute_metrics(name)
    except Exception as e:
        print(f"  [{i}] {name}: error {e}")
        m = {"engagement": None, "valence": None, "n_posts": None, "posts": []}

    for p in m.pop("posts", []):
        posts_records.append({
            "app_id": row.get("app_id"),
            "game_name": name,
            "title": p.get("title"),
            "score": p.get("score"),
            "upvote_ratio": p.get("upvote_ratio"),
            "num_comments": p.get("num_comments"),
            "created_utc": pd.to_datetime(p.get("created_utc"), unit="s", errors="coerce"),
            "permalink": "https://www.reddit.com" + (p.get("permalink") or ""),
        })

    record = row.to_dict()
    record.update(m)
    results.append(record)

    if (i + 1) % 10 == 0:
        print(f"  [{i+1:>3}/{len(games_list)}] {name[:30]:<30} engagement={m['engagement']}  n={m['n_posts']}")

    if (i + 1) % 25 == 0:
        pd.DataFrame(results).to_csv(OUTPUT_CSV, index=False)
        pd.DataFrame(posts_records).to_csv(POSTS_CSV, index=False)

    time.sleep(REQUEST_DELAY)

pd.DataFrame(results).to_csv(OUTPUT_CSV, index=False)
pd.DataFrame(posts_records).to_csv(POSTS_CSV, index=False)
print(f"\nDone. Saved {len(results)} games to {OUTPUT_CSV.name} and {len(posts_records)} posts to {POSTS_CSV.name}.")

  [ 10/1923] EA SPORTS™ FIFA 21             engagement=510  n=22
  [ 20/1923] MapleStory                     engagement=86  n=6
  [ 30/1923] Cube Racer                     engagement=0  n=0
  [ 40/1923] Verdun                         engagement=125  n=5
  [ 50/1923] A Plague Tale: Innocence       engagement=403  n=4
  [ 60/1923] DRAGON BALL FighterZ           engagement=3268  n=7
  [ 70/1923] Subsistence                    engagement=290  n=5
  [ 80/1923] Ravenfield                     engagement=6  n=3
  [ 90/1923] Pavlov                         engagement=1492  n=9
  [100/1923] Dishonored                     engagement=53233  n=8
  [110/1923] Secret Neighbor                engagement=0  n=0
  [120/1923] Warhammer 40,000: Space Marine engagement=0  n=0
  [130/1923] Stronghold Crusader HD         engagement=0  n=0
  [140/1923] Batman™: Arkham Origins        engagement=5750  n=4
  [150/1923] Cyber Manhunt                  engagement=0  n=0
  [160/1923] Hydroneer                      engagement=15  n=5
  [170/1923] Assassin's Creed® Unity        engagement=26089  n=4
  [180/1923] ACE COMBAT™7: SKIES UNKNOWN    engagement=119  n=8
  [190/1923] DCS World Steam Edition        engagement=0  n=0
  [200/1923] HELLDIVERS™                    engagement=372186  n=61
  [210/1923] Counter-Strike Nexon           engagement=0  n=0
  [220/1923] SWORD ART ONLINE Alicization L engagement=0  n=0
  [230/1923] Nioh: Complete Edition         engagement=1608  n=22
  [240/1923] Pixel Puzzles Ultimate Jigsaw  engagement=0  n=0
  [250/1923] Forts                          engagement=25  n=1
  [260/1923] 恐惧之间 Fear surrounds            engagement=0  n=0
  [270/1923] Age of History II              engagement=0  n=0
  [280/1923] Golf With Your Friends         engagement=14  n=6
  [290/1923] Danganronpa: Trigger Happy Hav engagement=0  n=0
  [300/1923] PULSAR: Lost Colony            engagement=9  n=2
  [310/1923] X4: Foundations                engagement=4  n=1
  [320/1923] Iron Harvest                   engagement=0  n=0
  [330/1923] Karos                          engagement=0  n=0
  [340/1923] Labyronia RPG 2                engagement=0  n=0
  [350/1923] Two Worlds: Epic Edition       engagement=0  n=0
  [360/1923] NOBUNAGA'S AMBITION: Sphere of engagement=0  n=0
  [370/1923] Idling to Rule the Gods        engagement=0  n=0
  [380/1923] Champions Online               engagement=0  n=0
  [390/1923] GWENT: The Witcher Card Game   engagement=0  n=0
  [400/1923] Secret World Legends           engagement=0  n=0
  [410/1923] The Tenants                    engagement=0  n=0
  [420/1923] Space Haven                    engagement=0  n=0
  [430/1923] A Hat in Time                  engagement=0  n=0
  [440/1923] Clone Drone in the Danger Zone engagement=6  n=1
  [450/1923] Far Cry® 3                     engagement=105743  n=5
  [460/1923] First Class Trouble            engagement=11  n=9
  [470/1923] A Way Out                      engagement=259  n=7
  [480/1923] Untitled Goose Game            engagement=11749  n=5
  [490/1923] Neverwinter                    engagement=7537  n=8
  [500/1923] LEGO® Worlds                   engagement=74357  n=6
  [510/1923] Miscreated                     engagement=0  n=0
  [520/1923] Awesomenauts                   engagement=0  n=0
  [530/1923] TrackMania Nations Forever     engagement=4  n=1
  [540/1923] ATLAS                          engagement=1176  n=3
  [550/1923] Warhammer 40,000: Gladius - Re engagement=0  n=0
  [560/1923] Subnautica                     engagement=169958  n=29
  [570/1923] Vendetta - Curse of Raven's Cr engagement=0  n=0
  [580/1923] OVR Advanced Settings          engagement=0  n=0
  [590/1923] SD GUNDAM G GENERATION CROSS R engagement=0  n=0
  [600/1923] Z1 Battle Royale               engagement=0  n=0
  [610/1923] Mitos.is: The Game             engagement=0  n=0
  [620/1923] Football Manager 2017          engagement=0  n=0
  [630/1923] Castle Crashers®               engagement=0  n=0
  [640/1923] PrprLive                       engagement=0  n=0
  [650/1923] Starship Annihilator           engagement=0  n=0
  [660/1923] Dragon Age™ Inquisition        engagement=2324  n=8
  [670/1923] Ghostrunner                    engagement=1158  n=24
  [680/1923] STAR WARS™ Empire at War: Gold engagement=29  n=5
  [690/1923] From the Depths                engagement=203  n=5
  [700/1923] Murderous Pursuits             engagement=0  n=0
  [710/1923] Sword Art Online: Hollow Reali engagement=0  n=0
  [720/1923] DRAGON QUEST BUILDERS™ 2       engagement=1  n=1
  [730/1923] Dead Rising 4                  engagement=0  n=0
  [740/1923] Poppy Playtime                 engagement=125  n=11
  [750/1923] King of Retail                 engagement=0  n=0
  [760/1923] Escape Room - The Sick Colleag engagement=0  n=0
  [770/1923] NBA 2K20                       engagement=2  n=2
  [780/1923] Depth                          engagement=20741  n=6
  [790/1923] Soccer Manager 2022            engagement=0  n=0
  [800/1923] Software Inc.                  engagement=1  n=2
  [810/1923] Frederic: Evil Strikes Back    engagement=0  n=0
  [820/1923] Dark and Light                 engagement=0  n=0
  [830/1923] Ticket to Ride                 engagement=0  n=0
  [840/1923] Turbo Pug                      engagement=0  n=0
  [850/1923] Freddy Fazbear's Pizzeria Simu engagement=0  n=0
  [860/1923] LET IT DIE                     engagement=2660  n=6
  [870/1923] Ultimate Custom Night          engagement=0  n=0
  [880/1923] Nebuchadnezzar                 engagement=0  n=0
  [890/1923] 部落与弯刀 Sands of Salzaar         engagement=0  n=0
  [900/1923] GTFO                           engagement=24  n=5
  [910/1923] PickCrafter                    engagement=0  n=0
  [920/1923] Teeworlds                      engagement=0  n=0
  [930/1923] Civil War: Battle of Petersbur engagement=0  n=0
  [940/1923] F1 2012                        engagement=0  n=0
  [950/1923] Attack on Titan 2 - A.O.T.2    engagement=0  n=0
  [960/1923] Stoneshard                     engagement=1  n=1
  [970/1923] Bad Rats                       engagement=0  n=0
  [980/1923] Neon Space 2                   engagement=0  n=0
  [990/1923] Spellcaster University         engagement=0  n=0
  [1000/1923] Mafia                          engagement=221688  n=17
  [1010/1923] Rogue Agent                    engagement=5  n=1
  [1020/1923] We Were Here                   engagement=20  n=7
  [1030/1923] Dungeon Munchies               engagement=0  n=0
  [1040/1923] Defence to death               engagement=0  n=0
  [1050/1923] FIVE NIGHTS AT FREDDY'S: HELP  engagement=0  n=0
  [1060/1923] SEUM: Speedrunners from Hell   engagement=0  n=0
  [1061] The Sims™ 3: error 503 Server Error: Service Unavailable for url: https://www.reddit.com/r/gaming/search.json?q=%22The+Sims+3%22&restrict_sr=1&sort=top&t=all&limit=100
  [1063] RIDE 3: error 503 Server Error: Service Unavailable for url: https://www.reddit.com/r/gaming/search.json?q=%22RIDE+3%22&restrict_sr=1&sort=top&t=all&limit=100
  [1070/1923] Quaver                         engagement=0  n=0
  [1080/1923] Partisans 1941                 engagement=0  n=0
  [1090/1923] Football Manager 2021 Touch    engagement=0  n=0
  [1100/1923] Spellsworn                     engagement=0  n=0
  [1110/1923] SpellForce 3: Versus Edition   engagement=0  n=0
  [1120/1923] Kao the Kangaroo: Round 2      engagement=0  n=0
  [1130/1923] Tastemaker                     engagement=0  n=0
  [1140/1923] Unheard                        engagement=32  n=5
  [1150/1923] Firework                       engagement=6898  n=6
  [1160/1923] Turing Complete                engagement=0  n=0
  [1170/1923] 英雄黄昏                           engagement=0  n=0
  [1180/1923] Road Redemption                engagement=0  n=0
  [1190/1923] King’s Bounty: Legions         engagement=0  n=0
  [1200/1923] Fake Hostel                    engagement=0  n=0
  [1210/1923] Patron                         engagement=74  n=2
  [1220/1923] Farm Manager 2021: Prologue    engagement=0  n=0
  [1230/1923] Northgard: Definitive Edition  engagement=35  n=3
  [1240/1923] MONMUSU                        engagement=0  n=0
  [1250/1923] FINAL FANTASY IV               engagement=62  n=4
  [1260/1923] RiMS Racing                    engagement=4  n=1
  [1270/1923] Sniper Fury                    engagement=0  n=0
  [1280/1923] Rising World                   engagement=0  n=0
  [1290/1923] 3on3 FreeStyle: Rebound        engagement=0  n=0
  [1300/1923] EverQuest II                   engagement=0  n=0
  [1310/1923] Farm Manager 2021              engagement=4  n=1
  [1320/1923] 東方剛欲異聞～ 水没した沈愁地獄               engagement=0  n=0
  [1330/1923] Cube Escape: Paradox           engagement=0  n=0
  [1340/1923] SpaceEngine                    engagement=0  n=0
  [1350/1923] Burnout™ Paradise Remastered   engagement=16  n=2
  [1360/1923] Marbles on Stream              engagement=0  n=0
  [1370/1923] Industries of Titan            engagement=0  n=0
  [1380/1923] Ymir                           engagement=0  n=0
  [1390/1923] DPS IDLE                       engagement=0  n=0
  [1400/1923] Motorcycle Mechanic Simulator  engagement=0  n=0
  [1410/1923] Cricket 22                     engagement=0  n=0
  [1420/1923] Tribal Wars                    engagement=0  n=0
  [1430/1923] My New Memories                engagement=0  n=0
  [1440/1923] Tanki Online                   engagement=141  n=5
  [1450/1923] Operation: New Earth           engagement=0  n=0
  [1460/1923] ELYON                          engagement=0  n=1
  [1470/1923] Tails Noir                     engagement=0  n=0
  [1480/1923] Fire Pro Wrestling World       engagement=0  n=0
  [1490/1923] Gedonia                        engagement=0  n=0
  [1500/1923] Get Stuffed!                   engagement=0  n=0
  [1510/1923] Circuit Superstars             engagement=7  n=1
  [1520/1923] GRIME                          engagement=2407  n=8
  [1530/1923] Puzzle Pirates                 engagement=0  n=0
  [1540/1923] The Coin Game                  engagement=0  n=0
  [1550/1923] PropHunter                     engagement=0  n=0
  [1560/1923] Arboria                        engagement=2  n=1
  [1570/1923] エルソード (ELSWORD)                engagement=0  n=0
  [1580/1923] Walkabout Mini Golf VR         engagement=0  n=0
  [1590/1923] The Fishing Club 3D: Co-op Spo engagement=0  n=0
  [1600/1923] Franchise Hockey Manager 7     engagement=0  n=0
  [1610/1923] Idle Monkeylogy                engagement=0  n=0
  [1620/1923] GTTOD                          engagement=2  n=1
  [1630/1923] MXGP 2021 - The Official Motoc engagement=0  n=0
  [1640/1923] Impostor Factory               engagement=0  n=0
  [1650/1923] KartKraft                      engagement=0  n=0
  [1660/1923] Draw & Guess                   engagement=0  n=0
  [1670/1923] Wartune Reborn                 engagement=0  n=0
  [1680/1923] Retimed                        engagement=0  n=0
  [1690/1923] Heroes & Generals              engagement=0  n=0
  [1700/1923] Rocket League                  engagement=23648  n=4
  [1710/1923] Frostpunk                      engagement=0  n=0
  [1720/1923] Hollow Knight                  engagement=205549  n=47
  [1730/1923] Disco Elysium - The Final Cut  engagement=0  n=0
  [1740/1923] Red Dead Online                engagement=23485  n=14
  [1750/1923] AdVenture Capitalist           engagement=31  n=2
  [1760/1923] XCOM® 2                        engagement=20  n=1
  [1770/1923] Nioh 2 – The Complete Edition  engagement=0  n=0
  [1780/1923] The Binding of Isaac: Rebirth  engagement=6  n=1
  [1790/1923] Borderlands 3                  engagement=136625  n=14
  [1800/1923] Melvor Idle                    engagement=0  n=0
  [1810/1923] Shop Titans                    engagement=0  n=0
  [1820/1923] Don't Starve                   engagement=153274  n=22
  [1830/1923] The Elder Scrolls V: Skyrim    engagement=42  n=2
  [1840/1923] Titan Quest Anniversary Editio engagement=100  n=4
  [1850/1923] Command & Conquer™ Remastered  engagement=0  n=0
  [1860/1923] DOOM Eternal                   engagement=210707  n=25
  [1870/1923] DARK SOULS™: REMASTERED        engagement=21  n=2
  [1880/1923] Mount & Blade: Warband         engagement=0  n=0
  [1890/1923] Fallout 76                     engagement=86849  n=16
  [1900/1923] Overcooked! 2                  engagement=3  n=1
  [1910/1923] Rome: Total War                engagement=56  n=3
  [1920/1923] SCP: Secret Laboratory         engagement=12  n=2

Done. Saved 1923 games to games_reddit.csv and 6502 posts to reddit_posts.csv.

## 8. Results

In [8]:
results_df = pd.read_csv(OUTPUT_CSV)

print(f"=== Games-level ({OUTPUT_CSV.name}) ===")
print(f"Total: {len(results_df)} games")
print(f"With at least one matching post: {(results_df['n_posts'] > 0).sum()}")
print(f"Mean engagement: {results_df['engagement'].mean():.1f}")
print(f"Mean valence:    {results_df['valence'].mean():.3f}")
display(results_df[["app_id", "game_name", "peak_players", "engagement", "valence", "n_posts"]].head(10))

if POSTS_CSV.exists():
    posts_df = pd.read_csv(POSTS_CSV, parse_dates=["created_utc"])
    print(f"\n=== Posts-level ({POSTS_CSV.name}) ===")
    print(f"Total posts: {len(posts_df)}")
    print(f"Date range:  {posts_df['created_utc'].min()}  →  {posts_df['created_utc'].max()}")
    print(f"Mean comments per post: {posts_df['num_comments'].mean():.1f}")
    display(posts_df[["game_name", "title", "score", "num_comments", "upvote_ratio", "created_utc"]].head(10))

=== Games-level (games_reddit.csv) ===
Total: 1923 games
With at least one matching post: 785
Mean engagement: 9877.3
Mean valence:    0.746

,app_id,game_name,peak_players,engagement,valence,n_posts
0,751780,Forager,999,2.0,0.530000,2.0
1,8500,EVE Online,999,18131.0,0.915000,4.0
2,628070,Romance of the Three Kingdoms XI with Power Up...,999,0.0,NaN,0.0
3,368500,Assassin's Creed Syndicate,999,1533.0,0.806000,5.0
4,366220,Wurm Unlimited,999,0.0,NaN,0.0
5,500,Left 4 Dead,999,162241.0,0.905385,13.0
6,1672740,崩壊3rd,999,0.0,NaN,0.0
7,1118200,People Playground,999,51.0,0.695556,9.0
8,838350,太吾绘卷 The Scroll Of Taiwu,999,0.0,NaN,0.0
9,1313860,EA SPORTS™ FIFA 21,999,510.0,0.597273,22.0

=== Posts-level (reddit_posts.csv) ===
Total posts: 6502
Date range:  2021-01-01 15:30:20  →  2025-12-31 19:52:58
Mean comments per post: 156.3

,game_name,title,score,num_comments,upvote_ratio,created_utc
0,Forager,Looking for a game like forager,2,2,0.56,2024-09-13 02:51:04
1,Forager,Forager Co-op,0,9,0.50,2022-09-24 14:22:57
2,EVE Online,The most expensive gameing war was unsurprisin...,13285,740,0.95,2022-05-16 23:37:40
3,EVE Online,One of the servers that powered EVE Online bac...,4378,150,0.98,2023-11-09 14:52:30
4,EVE Online,EVE Online | Down The Rabbit Hole | A 6 hour d...,330,57,0.87,2023-11-01 19:10:58
5,EVE Online,Latest Alliance Theft in EVE Online: Multiple ...,138,65,0.86,2023-11-21 22:21:54
6,Assassin's Creed Syndicate,Assassin’s Creed Syndicate 60 FPS/4k Console P...,928,129,0.94,2024-11-18 18:57:11
7,Assassin's Creed Syndicate,Assassin's Creed Syndicate is definetly one of...,511,252,0.73,2023-07-02 07:18:09
8,Assassin's Creed Syndicate,Started playing Assassin's Creed Syndicate and...,66,47,0.81,2022-06-03 15:02:07
9,Assassin's Creed Syndicate,i was playing assassin's Creed syndicate earli...,18,2,0.89,2022-10-04 14:52:51